services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
    container_name: container_app
    ports:
      - ${PORT}:${PORT}
    depends_on: [mysql]
  mysql:
    image: mysql:8.0.30-debian
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tickets
    ports:
      - 33060:3306
