export enum ErrorCode {
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_NOT_PROVIDED = 'AUTH_TOKEN_NOT_PROVIDED',

  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  USER_ACCESS_DENIED = 'USER_ACCESS_DENIED',

  RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND',
  PARTNER_ALREADY_EXIST = 'PARTNER_ALREADY_EXIST',
  CUSTOMER_ALREADY_EXIST = 'CUSTOMER_ALREADY_EXIST',

  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  PURCHASE_NOT_FOUND = 'PURCHASE_NOT_FOUND',
  CUSTOMER_NOT_FOUND = 'CUSTOMER_NOT_FOUND',

  PURCHASE_INVALID_STATE = 'PURCHASE_INVALID_STATE',

  TICKET_NOT_AVAILABLE = 'TICKET_NOT_AVAILABLE',
}
